// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDra5cvAwkPS3heZl3_eYN-yQghYecE6R0',
    appId: '1:257918056021:web:cde5ceda1b6e5efdb586dc',
    messagingSenderId: '257918056021',
    projectId: 'ecommerce-8c5a7',
    authDomain: 'ecommerce-8c5a7.firebaseapp.com',
    storageBucket: 'ecommerce-8c5a7.firebasestorage.app',
    measurementId: 'G-4F0WL3X4JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDwrJN8il7PknLXKnr8lNNh277co_YcsA',
    appId: '1:257918056021:android:1b355b621376240fb586dc',
    messagingSenderId: '257918056021',
    projectId: 'ecommerce-8c5a7',
    storageBucket: 'ecommerce-8c5a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBymiLcJTeoEsbEgk6R6ovewp59jamcJhQ',
    appId: '1:257918056021:ios:4376b24e86481d4db586dc',
    messagingSenderId: '257918056021',
    projectId: 'ecommerce-8c5a7',
    storageBucket: 'ecommerce-8c5a7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBymiLcJTeoEsbEgk6R6ovewp59jamcJhQ',
    appId: '1:257918056021:ios:4376b24e86481d4db586dc',
    messagingSenderId: '257918056021',
    projectId: 'ecommerce-8c5a7',
    storageBucket: 'ecommerce-8c5a7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDra5cvAwkPS3heZl3_eYN-yQghYecE6R0',
    appId: '1:257918056021:web:a4fe61e1fd7d7105b586dc',
    messagingSenderId: '257918056021',
    projectId: 'ecommerce-8c5a7',
    authDomain: 'ecommerce-8c5a7.firebaseapp.com',
    storageBucket: 'ecommerce-8c5a7.firebasestorage.app',
    measurementId: 'G-GM3B409RHS',
  );
}
